### ISSUE TITLE
vscode-pdf extension

### ISSUE THREAD

**Issue by WWWzq-01** [XieGuochao/csapp#4]
This extension has been updated to 1.1.0, but it is still 1.0.0 in docker, can you update it as soon as possible?

**Comment by XieGuochao** [comment]
Not really, sorry. Code server and VSCode are actually different and the team of code server is trying to support more extensions of VSCode. 
But we have failed to try to install 1.1.0 version in docker which simply does not work well. We will catch up with the latest version of code server and try to upgrade it ASAP.
Actually the 1.0.0 version works well on most machines and we can use it for now.
