### ISSUE TITLE
gdb can't run in docker with M1 chip

### ISSUE THREAD

**Issue by HomuraCat** [XieGuochao/csapp#5]
When I use the gdb in docker and try to run the code. It turns out as follows:
``` bash
(gdb) r
Starting program:  
warning: Error disabling address space randomization: Operation not permitted
No executable file specified.
Use the "file" or "exec-file" command.
```
Are there any ways to solve it?

**Comment by XieGuochao** [comment]
Fix with [Tag 1.6-arm64](https://github.com/XieGuochao/csapp/releases/tag/1.6-arm64).

**Comment by BDXGD** [comment]
Is it fixed ?

**Comment by BDXGD** [comment]
> When I use the gdb in docker and try to run the code. It turns out as follows:
> 
> ```shell
> (gdb) r
> Starting program:  
> warning: Error disabling address space randomization: Operation not permitted
> No executable file specified.
> Use the "file" or "exec-file" command.
> ```
> 
> Are there any ways to solve it?

Hi, can you run successfully with m1 chip ?
